### ISSUE TITLE
Add internationalisation package

### ISSUE THREAD

**Issue by lawriecate** [mymizu/mymizu-web#11]
We want to allow the website to function in english and japanese, so please research and install an appropriate i18n package !

There are placeholder links to switch the language in the menu

The language strings for the interface should be able to be stored as JSON strings
The API can also be configured to request information in Japanese and English based on the interface locale setting

**Comment by be-anna** [comment]
Please check notion link for more details:
https://mymizu.notion.site/English-and-japanese-support-f7a6666a540442baa78db306de414013

**Comment by xiankai** [comment]
The i18n configuration for google maps can be found here:

https://github.com/google-map-react/google-map-react/blob/master/API.md#bootstrapurlkeys-object

Example:
```
<GoogleMap
  bootstrapURLKeys={{
    key: API_KEY,
    language: 'ru',
    region: 'ru',
    libraries:['places'],
    ...otherUrlParams,
  }}
>
```

**Comment by gianferrer** [comment]
This linked to PR #29
