### ISSUE TITLE
Add search feature

### ISSUE THREAD

**Issue by lawriecate** [mymizu/mymizu-web#14]
Using google maps autocomplete API, 
create a search bar that will let users type in placenames and when they select a place, recentre the map

<img width="316" alt="image" src="https://user-images.githubusercontent.com/3129607/178089822-a2e9e7cb-82d9-4853-93ed-2550eeb8fa36.png">
https://www.figma.com/file/HfT3GwZlpR6q9RScMNdF5D/mymizu-Web-App?node-id=0%3A1

**Comment by be-anna** [comment]
Please check notion link for more details:
https://mymizu.notion.site/Searching-on-map-81e3f2506abd40698c4e9d308da492ad
