### ISSUE TITLE
Fix translation for spot modal 

### ISSUE THREAD

**Issue by lawriecate** [mymizu/mymizu-web#34]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/3129607/189280190-27899caf-1330-4050-99c2-84a27cedb9c6.png">

Route , share, add feedback etc should have Japanese translations based on figma translations
https://www.figma.com/file/HfT3GwZlpR6q9RScMNdF5D/mymizu-Web-App?node-id=728%3A12433

**Comment by alvihrhp** [comment]
Hi @lawriecate, can you explain more about this issue. Because i still i don't understand it, since i18n language translation is done manually. Thank you !

**Comment by gianferrer** [comment]
Hi @lawriecate we just had a quick discussion on this and as we understand it we need to translate the following strings:

Route - ルート
Share - シェア
Feedback - フィードバック

**Comment by gianferrer** [comment]
PR - https://github.com/mymizu/mymizu-web/pull/37
