### ISSUE TITLE
Create route to display information about single refill spot

### ISSUE THREAD

**Issue by lawriecate** [mymizu/mymizu-web#4]
When you click a marker, or access it via a permalink like
https://{APP_URL}/refill_spots/{refill_spot_slug}

It should:

- Load information about the refill spot
- Centre the map at the coordinates, refresh the map
- Show the pop up of individual refill spot info 

Reference: https://www.figma.com/file/HfT3GwZlpR6q9RScMNdF5D/mymizu-Web-App?node-id=0%3A1

**Comment by be-anna** [comment]
https://mymizu.notion.site/Copy-share-link-for-Refill-Spot-Page-89e414fc14e24998832702ba46a86a0b
