### ISSUE TITLE
Show individual refill spot info on click marker

### ISSUE THREAD

**Issue by lawriecate** [mymizu/mymizu-web#5]
When you click a marker, it should show a pop up with detailed information about the refill spot
<img width="597" alt="image" src="https://user-images.githubusercontent.com/3129607/178089130-6a9b961f-d093-4564-99a2-be4472248bf9.png">

Reference: https://www.figma.com/file/HfT3GwZlpR6q9RScMNdF5D/mymizu-Web-App?node-id=0%3A1

**Comment by be-anna** [comment]
Profile page for refill partners:
https://mymizu.notion.site/Profile-page-for-refill-partners-635f83b02f2b40a38587c4c39bcaec89
Public refill spots:
https://mymizu.notion.site/Information-page-for-public-refill-spots-21d1a5afc5964a63a7da7d8547ee8799

**Comment by gianferrer** [comment]
This is linked to #30
