### ISSUE TITLE
Show usage mymizu statistics 

### ISSUE THREAD

**Issue by lawriecate** [mymizu/mymizu-web#6]
Beneath the map, load the total refill amount from the `community` endpoint and display statistics
<img width="461" alt="image" src="https://user-images.githubusercontent.com/3129607/178089156-0a5e9f08-254e-4a3f-a909-3e5c89e51e4f.png">

- Pet bottle amount is defined as refill amount ml / 500
- CO2 amount is defined as total pet bottles *  0.333
- Litres is refill amount ml / 1000

**Comment by be-anna** [comment]
Please check notion link for more details:
https://mymizu.notion.site/Live-community-metrics-ae5eab9dfc394c08818b65f059e02234

**Comment by lawriecate** [comment]
https://sites.google.com/mymizu.co/mymizuapi/home
