### ISSUE TITLE
Show a fun fact on app load

### ISSUE THREAD

**Issue by lawriecate** [mymizu/mymizu-web#7]
### Description

Show fun facts related to sustainability and mymizu to onboard user onto the site and keep them engaged

### User Journey

1. Once user is on the map and looking at the page he can see some fun facts related to sustainability
2. This fun facts changes in some moment of time

### Specs

- Show one fun fact at a time with emoji
- For PC version: it will stay on the map constantly and change fun fact message once every 1 minute
- For mobile version: it will pop up on the screen and user can minimize it
- Both: there can be a small waterdrop icon on the screen, so user can click on it and see fun facts anytime

![image](https://user-images.githubusercontent.com/3129607/178089234-d6149e51-8e34-493d-9672-9e83d8d9c7bc.png)

- **Example Fun Facts**
    - 740 plastic bottles are bought in Japan every second.
    - More than 8 million tons of plastic are dumped into our oceans every year.
    - Approximately 2 million plastic bags are used every minute around the world.
    - The average plastic bag is used for only 12 minutes!
    - Global plastic production has doubled in the past 50 years.
    - It's estimated that 50% of the plastic we consume is used just once and thrown away.
    - Approximately 90 percent of all trash floating on the ocean's surface is plastic, with 46,000 pieces of plastic per square mile.
    - There are over 5 trillion pieces of plastic in our oceans – enough to circle the Earth over 400 times.
    - Japan is the world's second-biggest producer per capita of plastic waste behind the U.S.
    - Over 25 billion PET bottle products are produced every year in Japan, equal to approximately 180 bottles per person.
    - By 2050, it is estimated that there will be more plastic than fish in the sea.

**Comment by be-anna** [comment]
Please check notion link for more details:
https://mymizu.notion.site/Popup-showing-key-s-or-Fun-Facts-upon-app-open-712bc5f9a4974817a5a88ac7fe6a7eea
