### ISSUE TITLE
Add side menu links

### ISSUE THREAD

**Issue by lawriecate** [mymizu/mymizu-web#8]
### Description

A side menu with links to other mymizu and sustainability related resources

The repo already includes a basic menu, so please check with mymizu members and add needed links to social media and other links

### Design

![image](https://user-images.githubusercontent.com/3129607/178089283-d4926716-39c0-4459-bc0c-d2d22b3128e5.png)

**Comment by be-anna** [comment]
Please check notion link for more details:
https://mymizu.notion.site/mymizu-Information-Menu-836971c3eeac40ed8bcb9b5b6c63e8c3
