### ISSUE TITLE
When map is moved, reload refill spots and display

### ISSUE THREAD

**Issue by lawriecate** [mymizu/mymizu-web#9]
Currently the map only loads spots once on load, so we want to change behaviour so it calls the API and updates the map when it gets moved.

Please change the API interface to use the `POST /taps/search` endpoint, instead of `GET /taps/nearby`

The coordinate bounding box should be based on the current map bounding box the user is viewing

**Comment by gianferrer** [comment]
#22

**Comment by gianferrer** [comment]
This linked to PR # # #28
